/**
 * ipc.ts — Typed wrappers around Tauri invoke() for every Section B command.
 * Import types from ../bindings/ (generated by ts-rs from shared/src/lib.rs).
 */

import { invoke } from "@tauri-apps/api/core";

// ─── Re-export bindings (generated by ts-rs during `cargo build -p shared`) ──
// These files are auto-generated — do not edit by hand.
// Run `cargo build -p shared` to regenerate after changing shared/src/lib.rs

// ─── Auth Commands ─────────────────────────────────────────────────────────────

export interface SessionInfo {
  session_id: string;
  username: string;
  role: "SuperAdmin" | "Admin" | "Investigator" | "Auditor" | "ReadOnly" | "RecoveryAdmin";
  expires_at: string;
}

export interface KeyDisplayBundle {
  split_key_parts: string[] | null;
  recovery_key: string;
  generated_at: string;
}

export interface Settings {
  session_timeout_minutes: number;
  max_login_attempts: number;
  lockout_duration_secs: number;
  realtime_integrity_alerts: boolean;
}

export interface FortiChainError {
  code: string;
  detail?: Record<string, unknown>;
}

export async function adminSetup(username: string, password: string): Promise<KeyDisplayBundle> {
  return invoke("admin_setup", { username, password });
}

export async function login(username: string, password: string): Promise<SessionInfo> {
  return invoke("login", { username, password });
}

export async function logout(sessionId: string): Promise<void> {
  return invoke("logout", { sessionId });
}

export async function changePassword(sessionId: string, oldPw: string, newPw: string): Promise<void> {
  return invoke("change_password", { sessionId, oldPw, newPw });
}

export async function createReadonlyUser(sessionId: string, username: string, password: string): Promise<void> {
  return invoke("create_readonly_user", { sessionId, username, password });
}

export async function getSettings(sessionId: string): Promise<Settings> {
  return invoke("get_settings", { sessionId });
}

export async function updateSettings(sessionId: string, settings: Settings): Promise<void> {
  return invoke("update_settings", { sessionId, settings });
}

export async function getAppLogTail(sessionId: string, nLines: number): Promise<string> {
  return invoke("get_app_log_tail", { sessionId, nLines });
}

// ─── Folder Commands ──────────────────────────────────────────────────────────

export type ProtectedItemState = "Idle" | "Protecting" | "Protected" | "Unprotecting" | "CrashRecoveryPending";

export interface ProtectedItem {
  id: number;
  path: string;
  state: ProtectedItemState;
  protected_at: string | null;
  protected_by: string | null;
  files_processed: number;
  files_total: number | null;
}

export interface JobHandle {
  job_id: string;
}

export async function listProtectedItems(sessionId: string): Promise<ProtectedItem[]> {
  return invoke("list_protected_items", { sessionId });
}

export async function protectFolder(sessionId: string, path: string): Promise<JobHandle> {
  return invoke("protect_folder", { sessionId, path });
}

export async function unprotectFolder(
  sessionId: string,
  itemId: number,
  keyParts: string[]
): Promise<void> {
  return invoke("unprotect_folder", { sessionId, itemId, keyParts });
}

export async function resumeCrashRecovery(sessionId: string, itemId: number): Promise<void> {
  return invoke("resume_crash_recovery", { sessionId, itemId });
}

// ─── Audit Commands ───────────────────────────────────────────────────────────

export interface AuditEntry {
  id: number;
  timestamp: string;
  user: string | null;
  action: string;
  detail: string | null;
  chain_hash: string;
}

export interface AuditFilter {
  since?: string;
  until?: string;
  action_contains?: string;
  limit?: number;
  after_id?: number;
}

export interface ChainVerificationResult {
  intact: boolean;
  mismatch_at: number | null;
  entries_checked: number;
}

export async function getAuditLog(sessionId: string, filter: AuditFilter): Promise<AuditEntry[]> {
  return invoke("get_audit_log", { sessionId, filter });
}

export async function verifyAuditChain(sessionId: string): Promise<ChainVerificationResult> {
  return invoke("verify_audit_chain", { sessionId });
}

// ─── Recovery Commands ────────────────────────────────────────────────────────

export async function submitRecoveryKey(key: string): Promise<void> {
  return invoke("submit_recovery_key", { key });
}

export async function regenerateRecoveryKey(sessionId: string): Promise<KeyDisplayBundle> {
  return invoke("regenerate_recovery_key", { sessionId });
}
